CC = gcc

KERNEL_CC      = gcc
KERNEL_AR      = ar
KERNEL_LD      = ld
KERNEL_ASM     = fasm
KERNEL_OBJDUMP = objdump
KERNEL_OBJCOPY = objcopy
KERNEL_CFLAGS  = -fno-pic -static -fno-strict-aliasing -O2 -Wall -m32 -fno-omit-frame-pointer -I../include
